app:
  port: 3001
  swagger: true
  passwordSecret: 'race'
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'race_nestjs_admin'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    bigNumberStrings: false
    timezone": "local"
redis:
  - name: 'auth'
    host: 'localhost'
    port: 6379
    db: 0
    # keyPrefix: 'auth:'
  - name: 'admin'
    host: 'localhost'
    port: 6379
    db: 1
    # keyPrefix: 'admin:'
  - name: 'app'
    port: 6379
    db: 2
    # keyPrefix: 'app:'

jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '12h'
  refreshExpiresIn: '24h'

permissions:
  close: true
